application: asint
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: server.py

libraries:
- name: ssl
  version: latest
- name: webapp2
  version: "2.5.2"
#- url: /(.*\.(jpg))
#  static_files: static/\4
#  upload:  api/browser/static/js/(.*\.(jpg))

#- url: /(.*\.(tlp))
#  static_files: static/\5
#  upload:  api/browser/views/(.*\.(tlp))
